Feat adapt substrate relay message to interface
icon-project/btp pull request #60
Opened 2021-06-07 13:33 UTC by trmaphi

What this PR does

- [ ] Add support for BlockUpdate in pra.receiver
- [ ] Add support for Event Decoding for Edgeware
- [ ] Temporarily disable metadata mutex causing a bug in pra client.
- [ ] Correct RelayMessage.StateProof data must read from `state_getReadProof` RPC-API
- [ ] Add some unit tests.

2021-06-07 15:20 UTC, canhlinh requested changes

2021-06-07 15:20 UTC, canhlinh commented on chain/pra/client.go
> +// func (c *Client) getMetadata() *stypes.Metadata {
@trmaphi just replace by this 
```
func (c *Client) getMetadata() (*Metadata, error) {
   return c.subAPI.RPC.State.GetMetadataLatest();
}
```

2021-06-07 15:20 UTC, canhlinh commented on chain/pra/events.go
> +	ChainBridge_FungibleTransfer        []EventFungibleTransfer               //nolint:stylecheck,golint
Please remove all properties related to ChainBridge such as ChainBridge_FungibleTransfer. We don't need them.

2021-06-07 15:36 UTC, trmaphi commented
@canhlinh I resolved all discussions

2021-06-08 03:38 UTC, canhlinh approved these changes

2021-06-08 03:39 UTC, merged